### ISSUE TITLE
procenv FTBFS with gcc-10 when used with -Werror=format-overflow=

### ISSUE THREAD

**Issue by matthewruffell** [jamesodhunt/procenv#15]
Current master branch fails to build from source when attempting to build on 
Ubuntu 20.10 Groovy Gorilla with GCC version (Ubuntu 10.2.0-3ubuntu1) 10.2.0

Details:

```
gcc -DHAVE_CONFIG_H -I. -I..  -I . -I ./platform  -I ./platform/linux -D PROCENV_PLATFORM_LINUX          -pedantic -std=gnu99 -Wall -Wunused -fstack-protector -Wformat  -fdata-sections -ffunction-sections -Werror -g -O2 -MT platform/linux/procenv-platform.o -MD -MP -MF platform/linux/.deps/procenv-platform.Tpo -c -o platform/linux/procenv-platform.o `test -f 'platform/linux/platform.c' || echo './'`platform/linux/platform.c
platform/linux/platform.c: In function ‘handle_proc_branch_linux’:
platform/linux/platform.c:1266:21: error: ‘%s’ directive writing up to 1017 bytes into a region of size 16 [-Werror=format-overflow=]
 1265 |     p += 1+strlen ("Name:"); /* jump over tab char */
      |     ~~~~~~~~~~~~~~~~~~~~~~~
 1266 |     sprintf (name, "%s", p);
      |                     ^~
In file included from /usr/include/stdio.h:867,
                 from ./platform.h:22,
                 from platform/linux/platform-linux.h:25,
                 from platform/linux/platform.c:19:
/usr/include/x86_64-linux-gnu/bits/stdio2.h:36:10: note: ‘__builtin___sprintf_chk’ output between 1 and 1018 bytes into a destination of size 16
   36 |   return __builtin___sprintf_chk (__s, __USE_FORTIFY_LEVEL - 1,
      |          ^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
   37 |       __bos (__s), __fmt, __va_arg_pack ());
      |       ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
platform/linux/platform.c:1271:21: error: ‘%s’ directive writing up to 1017 bytes into a region of size 16 [-Werror=format-overflow=]
 1270 |     p += 1+strlen ("PPid:"); /* jump over tab char */
      |     ~~~~~~~~~~~~~~~~~~~~~~~
 1271 |     sprintf (ppid, "%s", p);
      |                     ^~
In file included from /usr/include/stdio.h:867,
                 from ./platform.h:22,
                 from platform/linux/platform-linux.h:25,
                 from platform/linux/platform.c:19:
/usr/include/x86_64-linux-gnu/bits/stdio2.h:36:10: note: ‘__builtin___sprintf_chk’ output between 1 and 1018 bytes into a destination of size 16
   36 |   return __builtin___sprintf_chk (__s, __USE_FORTIFY_LEVEL - 1,
      |          ^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
   37 |       __bos (__s), __fmt, __va_arg_pack ());
      |       ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~

```

Builds fine with GCC 9 in Ubuntu 20.04, seems GCC 10 changed the behaviour of
-Werror=format-overflow.

**Comment by xnox** [comment]
@jamesodhunt can you add me as a collaborator, such that i can merge things?
